# -*- coding: utf-8 -*-
"""CliniX-Explainer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cME5fAeLLK2S3J5qhMz0sCqBr9mUqQ5Y

CliniX Explainer — v0.1
Model-agnostic explainability and audit engine for clinical ML.
Key capabilities in this MVP:
- Load a trained model (scikit-learn / XGBoost / LightGBM / CatBoost when pickled)
- Ingest a tabular dataset (CSV/Parquet)
- Compute global and local SHAP explanations (TreeExplainer when possible, else KernelExplainer)
- Basic bias audit by group (e.g., sex/age bins) with performance slice metrics (AUROC/APS if target available)
- Structured JSON result export
- Optional PDF/HTML dossier export (lightweight; PDF requires reportlab, else HTML fallback)

Usage (example):

    from explainer import Explainer

    exp = Explainer(
        model_path="models/readmission_xgb.pkl",
        data_path="data/test_set.csv",
        feature_map="metadata/features.yaml",   # optional
        id_column="patient_id",                 # optional
        target="readmitted"                     # optional (for metrics)
    )

    global_res = exp.run_global_explanation(sample_size=2000)
    local_res  = exp.run_local_explanation(patient_id=203, top_k=8)
    bias_res   = exp.run_bias_audit(group_col="sex")

    exp.export_json("reports/report.json", include=["global","local","bias"])  # choose what to include
    exp.export_report("reports/dossier.pdf")  # PDF if reportlab present else HTML fallback

Notes:
- Kernel SHAP can be slow; we auto-sample background data.
- For best performance with SHAP TreeExplainer, prefer tree-based models.
- Be sure your features in the dataset match those used by the model.
"""

from __future__ import annotations

import json
import os
import warnings
from dataclasses import dataclass, field
from typing import Any, Dict, Iterable, List, Optional, Tuple, Union

import numpy as np
import pandas as pd

# Optional deps
try:  # model loading
    import joblib  # type: ignore
except Exception:  # pragma: no cover
    joblib = None

try:
    import shap  # type: ignore
except Exception:  # pragma: no cover
    shap = None

try:
    from sklearn.metrics import roc_auc_score, average_precision_score
except Exception:  # pragma: no cover
    roc_auc_score = None
    average_precision_score = None

try:
    import yaml  # type: ignore
except Exception:  # pragma: no cover
    yaml = None

# Optional PDF export
try:
    from reportlab.lib.pagesizes import A4
    from reportlab.pdfgen import canvas as pdf_canvas
    from reportlab.lib.utils import simpleSplit
except Exception:  # pragma: no cover
    A4 = None
    pdf_canvas = None
    simpleSplit = None


TreeLikeTypes = (
    "XGBClassifier",
    "XGBRegressor",
    "LGBMClassifier",
    "LGBMRegressor",
    "CatBoostClassifier",
    "CatBoostRegressor",
    "RandomForestClassifier",
    "RandomForestRegressor",
    "GradientBoostingClassifier",
    "GradientBoostingRegressor",
    "ExtraTreesClassifier",
    "ExtraTreesRegressor",
    "DecisionTreeClassifier",
    "DecisionTreeRegressor",
)


@dataclass
class Explainer:
    model_path: Union[str, Any]
    data_path: Optional[str] = None
    feature_map: Optional[str] = None  # YAML describing feature dtypes/order/renames
    id_column: Optional[str] = None
    target: Optional[str] = None

    # runtime state
    model: Any = field(init=False, default=None)
    data: Optional[pd.DataFrame] = field(init=False, default=None)
    X: Optional[pd.DataFrame] = field(init=False, default=None)
    y: Optional[pd.Series] = field(init=False, default=None)
    feature_names_: Optional[List[str]] = field(init=False, default=None)

    # results cache
    global_result: Optional[Dict[str, Any]] = field(init=False, default=None)
    local_results: Dict[Any, Dict[str, Any]] = field(init=False, default_factory=dict)
    bias_result: Optional[Dict[str, Any]] = field(init=False, default=None)

    def __post_init__(self):
        self._ensure_dependencies()
        self.model = self._load_model(self.model_path)
        if self.data_path:
            self._load_data(self.data_path)
        if self.feature_map:
            self._apply_feature_map(self.feature_map)
        self._prepare_Xy()

    # -------------------------------
    # Dependency checks
    # -------------------------------
    def _ensure_dependencies(self) -> None:
        if joblib is None:
            raise ImportError("joblib is required to load models. Please `pip install joblib`. ")
        if shap is None:
            warnings.warn("SHAP not installed; explanations will be disabled until installed. `pip install shap`.")
        if yaml is None and self.feature_map is not None:
            warnings.warn("PyYAML not installed; ignoring feature_map. Install with `pip install pyyaml`.")

    # -------------------------------
    # Loading utilities
    # -------------------------------
    def _load_model(self, model_ref: Union[str, Any]):
        """Load a model from disk or accept an already-loaded object."""
        if not isinstance(model_ref, str):
            return model_ref
        if not os.path.exists(model_ref):
            raise FileNotFoundError(f"Model file not found: {model_ref}")
        model = joblib.load(model_ref)
        return model

    def _load_data(self, path: str) -> None:
        if not os.path.exists(path):
            raise FileNotFoundError(f"Data file not found: {path}")
        if path.lower().endswith(".csv"):
            df = pd.read_csv(path)
        elif path.lower().endswith(".parquet"):
            df = pd.read_parquet(path)
        else:
            raise ValueError("Unsupported data format. Use CSV or Parquet.")
        self.data = df

    def _apply_feature_map(self, yaml_path: str) -> None:
        if yaml is None:
            return
        if not os.path.exists(yaml_path):
            warnings.warn(f"Feature map YAML not found: {yaml_path}")
            return
        with open(yaml_path, "r", encoding="utf-8") as f:
            spec = yaml.safe_load(f) or {}
        # Supported keys: order, dtypes, rename
        if self.data is None:
            warnings.warn("Feature map provided but data not loaded yet. Skipping.")
            return
        df = self.data.copy()
        rename = spec.get("rename", {})
        if rename:
            df = df.rename(columns=rename)
        dtypes = spec.get("dtypes", {})
        for col, dt in dtypes.items():
            try:
                df[col] = df[col].astype(dt)
            except Exception as e:
                warnings.warn(f"Failed casting {col} to {dt}: {e}")
        order = spec.get("order")
        if order:
            missing = [c for c in order if c not in df.columns]
            if missing:
                warnings.warn(f"Columns in order not found in data: {missing}")
            df = df[[c for c in order if c in df.columns] + [c for c in df.columns if c not in order]]
        self.data = df

    def _prepare_Xy(self) -> None:
        if self.data is None:
            return
        df = self.data.copy()
        if self.id_column and self.id_column in df.columns:
            df = df.set_index(self.id_column, drop=False)
        if self.target and self.target in df.columns:
            self.y = df[self.target]
            df = df.drop(columns=[self.target])
        # Remove any obvious non-feature columns (id)
        if self.id_column and self.id_column in df.columns:
            X = df.drop(columns=[self.id_column])
        else:
            X = df
        # Keep only numeric or category (try to encode categories)
        for col in X.select_dtypes(include=["category"]).columns:
            X[col] = X[col].astype("string")
        # one-hot encode string/categorical columns deterministically
        non_num = X.select_dtypes(include=["object", "string", "category"]).columns
        if len(non_num) > 0:
            X = pd.get_dummies(X, columns=list(non_num), dummy_na=True)
        self.X = X
        self.feature_names_ = list(X.columns)

    # -------------------------------
    # Explainability: Global
    # -------------------------------
    def run_global_explanation(self, sample_size: int = 4000, random_state: int = 42) -> Dict[str, Any]:
        if shap is None:
            raise ImportError("SHAP is required. Please `pip install shap`.")
        if self.X is None:
            raise ValueError("No features loaded. Provide data_path with features.")
        X = self._subsample(self.X, n=sample_size, random_state=random_state)
        explainer = self._get_shap_explainer(X)
        shap_values = self._compute_shap_values(explainer, X)
        # Aggregate absolute mean importance
        imp = np.abs(shap_values).mean(axis=0)
        ranking = sorted(
            (
                {"feature": f, "importance": float(v)}
                for f, v in zip(self.feature_names_, imp)
            ),
            key=lambda x: x["importance"],
            reverse=True,
        )
        res = {
            "feature_importance": ranking,
            "n_samples": int(X.shape[0]),
            "method": self._explainer_name(explainer),
        }
        self.global_result = res
        return res

    # -------------------------------
    # Explainability: Local
    # -------------------------------
    def run_local_explanation(self, patient_id: Optional[Any] = None, row_index: Optional[int] = None, top_k: int = 10) -> Dict[str, Any]:
        if shap is None:
            raise ImportError("SHAP is required. Please `pip install shap`.")
        if self.X is None:
            raise ValueError("No features loaded.")
        if (patient_id is None) and (row_index is None):
            raise ValueError("Provide either patient_id or row_index.")
        x_row, pid = self._select_row(patient_id, row_index)
        explainer = self._get_shap_explainer(self.X)
        shap_vals = self._compute_shap_values(explainer, x_row)
        vals = shap_vals.reshape(-1)
        pairs = list(zip(self.feature_names_, vals))

        # Feature values for this row
        x_vals = x_row.iloc[0]  # Series indexed by feature names

        # Sort by absolute contribution
        pairs_sorted = sorted(pairs, key=lambda p: abs(p[1]), reverse=True)[:top_k]

        result = {
            "patient_id": pid,
            "top_contributors": [
                {
                    "feature": f,
                    "value": float(x_vals.get(f, np.nan)),
                    "shap_value": float(v),
                    "direction": "↑" if v > 0 else "↓",
                }
                for f, v in pairs_sorted
            ],
            "method": self._explainer_name(explainer),
        }

        # cache
        self.local_results[pid] = result
        return result

    # -------------------------------
    # Bias audit
    # -------------------------------
    def run_bias_audit(self, group_col: str, min_group_size: int = 30) -> Dict[str, Any]:
        if self.data is None or self.X is None:
            raise ValueError("Data not loaded.")
        if group_col not in self.data.columns:
            raise ValueError(f"Group column '{group_col}' not found in data.")

        # Predictions
        preds = self._predict_proba_or_value(self.X)
        df = self.data.copy()
        df["__pred__"] = preds
        if self.target and self.target in df.columns and roc_auc_score is not None:
            y_true = self.y.values if isinstance(self.y, pd.Series) else self.y
        else:
            y_true = None

        out: Dict[str, Any] = {"group_col": group_col, "groups": []}
        for g, sdf in df.groupby(group_col):
            if len(sdf) < min_group_size:
                continue
            entry: Dict[str, Any] = {"group": self._to_jsonable(g), "n": int(len(sdf))}
            entry["pred_mean"] = float(np.mean(sdf["__pred__"]))
            entry["pred_std"] = float(np.std(sdf["__pred__"]))
            if y_true is not None:
                # Align y_true with sdf index
                y_s = df.loc[sdf.index, self.target]
                try:
                    if sdf["__pred__"].nunique() > 1:
                        entry["auroc"] = float(roc_auc_score(y_s, sdf["__pred__"]))
                    if average_precision_score is not None:
                        entry["aps"] = float(average_precision_score(y_s, sdf["__pred__"]))
                except Exception as e:
                    entry["metric_error"] = str(e)
            out["groups"].append(entry)

        # Simple disparity signal
        if len(out["groups"]) >= 2:
            means = [g["pred_mean"] for g in out["groups"]]
            out["mean_gap"] = float(max(means) - min(means))
        self.bias_result = out
        return out

    # -------------------------------
    # Export
    # -------------------------------
    def export_json(self, path: str, include: Optional[Iterable[str]] = None) -> None:
        include = set(include or ["global", "local", "bias"])  # type: ignore
        payload: Dict[str, Any] = {
            "meta": {
                "n_rows": int(self.X.shape[0]) if self.X is not None else 0,
                "n_features": len(self.feature_names_ or []),
                "id_column": self.id_column,
                "target": self.target,
            },
        }
        if "global" in include and self.global_result is not None:
            payload["global"] = self.global_result
        if "local" in include and self.local_results:
            payload["local"] = self.local_results
        if "bias" in include and self.bias_result is not None:
            payload["bias"] = self.bias_result
        os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            json.dump(payload, f, ensure_ascii=False, indent=2)

    def export_report(self, path: str) -> str:
        """Export a short dossier to PDF if reportlab available, else HTML.
        Returns the output path actually written.
        """
        base_dir = os.path.dirname(path) or "."
        os.makedirs(base_dir, exist_ok=True)
        # Prepare content pieces
        title = "CliniX Explainability Dossier"
        sections = []
        if self.global_result:
            top5 = self.global_result.get("feature_importance", [])[:5]
            txt = "\n".join(f"- {t['feature']}: {t['importance']:.4f}" for t in top5)
            sections.append(("Global Importance (Top 5)", txt))
        if self.bias_result:
            groups = self.bias_result.get("groups", [])
            lines = [f"Group={g['group']} n={g['n']} mean={g['pred_mean']:.3f} std={g['pred_std']:.3f}" for g in groups]
            if "mean_gap" in self.bias_result:
                lines.append(f"Mean prediction gap: {self.bias_result['mean_gap']:.3f}")
            sections.append(("Bias Audit (summary)", "\n".join(lines)))
        if self.local_results:
            any_pid = next(iter(self.local_results.keys()))
            loc = self.local_results[any_pid]
            lines = [f"Patient={any_pid}"] + [f"  • {e['feature']}: {e['shap_value']:+.3f} {e['direction']}" for e in loc["top_contributors"]]
            sections.append(("Local Explanation (example)", "\n".join(lines)))

        if pdf_canvas is not None:
            self._export_pdf(path, title, sections)
            return path
        else:
            html_path = os.path.splitext(path)[0] + ".html"
            self._export_html(html_path, title, sections)
            return html_path

    # -------------------------------
    # Internals
    # -------------------------------
    def _predict_proba_or_value(self, X: pd.DataFrame) -> np.ndarray:
        m = self.model
        # Classifier proba → positive class, else decision_function, else predict
        if hasattr(m, "predict_proba"):
            p = m.predict_proba(X)
            if isinstance(p, (list, tuple)):
                p = p[0]
            if p.ndim == 2 and p.shape[1] >= 2:
                return p[:, -1]
            return p.ravel()
        if hasattr(m, "decision_function"):
            d = m.decision_function(X)
            return np.asarray(d).ravel()
        if hasattr(m, "predict"):
            return np.asarray(m.predict(X)).ravel()
        raise ValueError("Model does not support predict/decision_function/predict_proba.")

    def _get_shap_explainer(self, background_X: pd.DataFrame):
        m = self.model
        # Detect if tree-based by class name
        cls_name = m.__class__.__name__
        if shap is None:
            raise ImportError("SHAP not available")
        if any(t in cls_name for t in TreeLikeTypes):
            with warnings.catch_warnings():
                warnings.simplefilter("ignore")
                return shap.TreeExplainer(m, feature_names=self.feature_names_)
        # Fallback to KernelExplainer with background sampling
        bg = background_X.sample(min(200, len(background_X)), random_state=42) if len(background_X) > 200 else background_X
        f = lambda data: self._predict_proba_or_value(pd.DataFrame(data, columns=self.feature_names_))
        return shap.KernelExplainer(f, bg)

    def _compute_shap_values(self, explainer, X: pd.DataFrame) -> np.ndarray:
        if hasattr(explainer, "shap_values"):
            vals = explainer.shap_values(X)
            # shap may return list for multiclass; take last class
            if isinstance(vals, list):
                vals = vals[-1]
            return np.asarray(vals)
        # KernelExplainer returns values via shap_values
        return np.asarray(explainer.shap_values(X))

    def _subsample(self, X: pd.DataFrame, n: int, random_state: int) -> pd.DataFrame:
        if len(X) <= n:
            return X
        return X.sample(n, random_state=random_state)

    def _select_row(self, patient_id: Optional[Any], row_index: Optional[int]) -> Tuple[pd.DataFrame, Any]:
        if self.X is None:
            raise ValueError("No data loaded")
        if patient_id is not None:
            if self.id_column is None:
                raise ValueError("id_column is not set; cannot select by patient_id")
            if patient_id not in self.data.index:
                raise KeyError(f"patient_id {patient_id} not found")
            row = self.X.loc[[patient_id]]
            return row, patient_id
        # else by row index
        if row_index is None or row_index < 0 or row_index >= len(self.X):
            raise IndexError("row_index out of range")
        pid = self.data.index[row_index] if self.data is not None else row_index
        row = self.X.iloc[[row_index]]
        return row, pid

    def _explainer_name(self, explainer) -> str:
        return explainer.__class__.__name__

    def _to_jsonable(self, v: Any) -> Any:
        try:
            json.dumps(v)
            return v
        except Exception:
            return str(v)

    # -------------------------------
    # Simple exporters
    # -------------------------------
    def _export_pdf(self, path: str, title: str, sections: List[Tuple[str, str]]):
        if pdf_canvas is None or A4 is None:
            raise RuntimeError("reportlab is not available for PDF export.")
        c = pdf_canvas.Canvas(path, pagesize=A4)
        width, height = A4
        x_margin, y_margin = 40, 50

        def draw_wrapped(text: str, x: int, y: int, max_width: int, leading: int = 14):
            lines = simpleSplit(text, "Helvetica", 10, max_width)
            for line in lines:
                c.drawString(x, y, line)
                y -= leading
            return y

        # Title
        c.setFont("Helvetica-Bold", 16)
        c.drawString(x_margin, height - y_margin, title)
        y = height - y_margin - 30

        c.setFont("Helvetica", 10)
        # Meta
        meta = f"Rows: {self.X.shape[0] if self.X is not None else 0} | Features: {len(self.feature_names_ or [])}"
        y = draw_wrapped(meta, x_margin, y, width - 2 * x_margin)
        y -= 10

        for sec_title, body in sections:
            if y < 120:
                c.showPage()
                y = height - y_margin
            c.setFont("Helvetica-Bold", 12)
            c.drawString(x_margin, y, sec_title)
            y -= 18
            c.setFont("Helvetica", 10)
            y = draw_wrapped(body, x_margin, y, width - 2 * x_margin)
            y -= 12

        c.showPage()
        c.save()

    def _export_html(self, path: str, title: str, sections: List[Tuple[str, str]]):
        html = ["<html><head><meta charset='utf-8'><title>Dossier</title>",
                "<style>body{font-family:Arial,Helvetica,sans-serif;margin:24px;} h1{font-size:20px;} h2{font-size:16px;margin-top:24px;} pre{background:#f7f7f7;padding:12px;border-radius:6px;}</style>",
                "</head><body>"]
        html.append(f"<h1>{title}</h1>")
        meta = f"<p><b>Rows</b>: {self.X.shape[0] if self.X is not None else 0} | <b>Features</b>: {len(self.feature_names_ or [])}</p>"
        html.append(meta)
        for sec_title, body in sections:
            html.append(f"<h2>{sec_title}</h2>")
            html.append(f"<pre>{self._escape_html(body)}</pre>")
        html.append("</body></html>")
        with open(path, "w", encoding="utf-8") as f:
            f.write("\n".join(html))

    def _escape_html(self, s: str) -> str:
        return (
            s.replace("&", "&amp;")
             .replace("<", "&lt;")
             .replace(">", "&gt;")
        )


# ---- If this file is executed directly, run a tiny smoke test (optional) ----
if __name__ == "__main__":
    print("CliniX Explainer v0.1 — module loaded. Create an Explainer() in your pipeline.")