# -*- coding: utf-8 -*-
"""CliniX-WebUI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rznOM9K3vITkRbXLGwOb0ZPWy2D0BnCe

#How to run it

### 1. Install deps (example):

`pip install fastapi uvicorn shap joblib scikit-learn pandas numpy pyyaml`

> reportlab is optional for PDF, but not needed for this UI


### 2. Run the app:

`uvicorn main:app --reload`


### 3. Open in browser:
http://localhost:8000
"""

# main.py
from __future__ import annotations

import os
import shutil
import tempfile
from typing import Optional

from fastapi import FastAPI, UploadFile, File, Form
from fastapi.responses import HTMLResponse, JSONResponse
from fastapi.middleware.cors import CORSMiddleware

from clinix_explainer import Explainer

app = FastAPI(title="ClinXAI Web UI", version="0.1")

# Allow local use from browser tools
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


INDEX_HTML = """
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>ClinXAI – Explainability Dossier</title>
  <style>
    body { font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
           margin: 24px; background:#0f172a; color:#e5e7eb; }
    h1 { font-size: 24px; margin-bottom: 4px; }
    h2 { font-size: 18px; margin-top: 24px; }
    .card { background:#020617; border-radius:12px; padding:16px; margin-top:16px;
            border:1px solid #1f2937; box-shadow:0 10px 25px rgba(0,0,0,.4);}
    label { display:block; margin-top:8px; font-size:14px; }
    input[type="text"], input[type="number"] {
        width:100%; padding:6px 8px; margin-top:4px; border-radius:8px;
        border:1px solid #4b5563; background:#020617; color:#e5e7eb;
    }
    input[type="file"] {
        margin-top:4px; font-size:13px;
    }
    button {
        margin-top:16px; padding:10px 18px; border-radius:999px; border:none;
        cursor:pointer; font-weight:600; background:linear-gradient(135deg,#22c55e,#0ea5e9);
        color:#020617;
    }
    button:disabled { opacity:0.6; cursor:wait; }
    pre {
        background:#020617; border-radius:8px; padding:12px;
        font-size:12px; overflow-x:auto; border:1px solid #1f2937;
    }
    table { width:100%; border-collapse:collapse; margin-top:8px; font-size:13px; }
    th, td { border-bottom:1px solid #1f2937; padding:6px 4px; text-align:left; }
    th { font-weight:600; color:#9ca3af; }
    code { background:#020617; padding:2px 4px; border-radius:4px; }
    .pill { display:inline-block; padding:2px 8px; border-radius:999px; font-size:11px;
            background:#1f2937; color:#e5e7eb; margin-left:4px;}
    .small { font-size:12px; color:#9ca3af; }
  </style>
</head>
<body>
  <h1>ClinXAI – Explainability Dossier</h1>
  <p class="small">
    Upload a trained model and a tabular dataset to generate global & local explanations,
    plus a basic bias audit suitable for hospital review.
  </p>

  <div class="card">
    <form id="analyze-form">
      <h2>1. Inputs</h2>
      <label>Model file (.pkl)
        <input type="file" name="model_file" required>
      </label>
      <label>Data file (.csv or .parquet)
        <input type="file" name="data_file" required>
      </label>

      <label>Patient ID column (optional)
        <input type="text" name="id_column" placeholder="e.g. patient_id">
      </label>
      <label>Target column (optional, for metrics & bias)
        <input type="text" name="target" placeholder="e.g. readmitted">
      </label>
      <label>Bias group column (optional)
        <input type="text" name="group_col" placeholder="e.g. sex">
      </label>
      <label>Patient row index for local explanation (optional)
        <input type="number" name="patient_row_index" min="0" placeholder="0 for first row">
      </label>

      <button type="submit" id="run-btn">Run analysis</button>
      <span id="status" class="small"></span>
    </form>
  </div>

  <div class="card">
    <h2>2. Global Feature Importance <span class="pill">Top 15</span></h2>
    <div id="global-container" class="small">No results yet.</div>
  </div>

  <div class="card">
    <h2>3. Local Explanation (single patient)</h2>
    <div id="local-container" class="small">No results yet.</div>
  </div>

  <div class="card">
    <h2>4. Bias Audit (by group)</h2>
    <div id="bias-container" class="small">No results yet.</div>
  </div>

  <script>
    const form = document.getElementById('analyze-form');
    const runBtn = document.getElementById('run-btn');
    const statusEl = document.getElementById('status');
    const globalEl = document.getElementById('global-container');
    const localEl = document.getElementById('local-container');
    const biasEl = document.getElementById('bias-container');

    form.addEventListener('submit', async (evt) => {
      evt.preventDefault();
      const fd = new FormData(form);
      runBtn.disabled = true;
      statusEl.textContent = "Running analysis…";

      try {
        const res = await fetch('/analyze', {
          method: 'POST',
          body: fd
        });
        if (!res.ok) {
          const text = await res.text();
          throw new Error(text || 'Request failed');
        }
        const data = await res.json();
        statusEl.textContent = "Done";

        renderGlobal(data.global);
        renderLocal(data.local);
        renderBias(data.bias);
      } catch (err) {
        console.error(err);
        statusEl.textContent = "Error: " + err.message;
        globalEl.textContent = "No results (error).";
        localEl.textContent = "No results (error).";
        biasEl.textContent = "No results (error).";
      } finally {
        runBtn.disabled = false;
      }
    });

    function renderGlobal(global) {
      if (!global || !global.feature_importance || global.feature_importance.length === 0) {
        globalEl.textContent = "No global explanation available.";
        return;
      }
      const top = global.feature_importance.slice(0, 15);
      let html = '<table><thead><tr><th>#</th><th>Feature</th><th>Importance (|SHAP| mean)</th></tr></thead><tbody>';
      top.forEach((row, idx) => {
        html += `<tr><td>${idx+1}</td><td><code>${row.feature}</code></td><td>${row.importance.toFixed(4)}</td></tr>`;
      });
      html += '</tbody></table>';
      html += `<p class="small">Method: ${global.method}, N samples: ${global.n_samples}</p>`;
      globalEl.innerHTML = html;
    }

    function renderLocal(local) {
      if (!local || !local.top_contributors) {
        localEl.textContent = "No local explanation available.";
        return;
      }
      let html = '';
      html += `<p class="small">Patient ID / index: <code>${local.patient_id}</code></p>`;
      html += '<table><thead><tr><th>Feature</th><th>Value</th><th>SHAP</th><th>Direction</th></tr></thead><tbody>';
      local.top_contributors.forEach((e) => {
  const shapVal = e.shap_value.toFixed(4);
  const featVal = (e.value === null || e.value === undefined || Number.isNaN(e.value))
    ? '-'
    : (Math.abs(e.value) >= 1000 || (Math.abs(e.value) > 0 && Math.abs(e.value) < 0.001))
      ? Number(e.value).toExponential(3)
      : Number(e.value).toFixed(4);

  html += `<tr>
    <td><code>${e.feature}</code></td>
    <td>${featVal}</td>
    <td>${shapVal}</td>
    <td>${e.direction}</td>
  </tr>`;
});

      html += '</tbody></table>';
      html += `<p class="small">Method: ${local.method}</p>`;
      localEl.innerHTML = html;
    }

    function renderBias(bias) {
      if (!bias || !bias.groups || bias.groups.length === 0) {
        biasEl.textContent = "No bias audit results (maybe no group_col/target provided).";
        return;
      }
      let html = `<p class="small">Grouping column: <code>${bias.group_col}</code></p>`;
      html += '<table><thead><tr><th>Group</th><th>n</th><th>Pred mean</th><th>Pred std</th><th>AUROC</th><th>APS</th></tr></thead><tbody>';
      bias.groups.forEach((g) => {
        html += `<tr>
          <td><code>${g.group}</code></td>
          <td>${g.n}</td>
          <td>${g.pred_mean.toFixed(3)}</td>
          <td>${g.pred_std.toFixed(3)}</td>
          <td>${g.auroc !== undefined ? g.auroc.toFixed(3) : '-'}</td>
          <td>${g.aps !== undefined ? g.aps.toFixed(3) : '-'}</td>
        </tr>`;
      });
      html += '</tbody></table>';
      if (bias.mean_gap !== undefined) {
        html += `<p class="small">Mean prediction gap across groups: <b>${bias.mean_gap.toFixed(3)}</b></p>`;
      }
      biasEl.innerHTML = html;
    }
  </script>
</body>
</html>
"""


@app.get("/", response_class=HTMLResponse)
async def index() -> HTMLResponse:
    return HTMLResponse(INDEX_HTML)


@app.post("/analyze")
async def analyze(
    model_file: UploadFile = File(...),
    data_file: UploadFile = File(...),
    id_column: Optional[str] = Form(None),
    target: Optional[str] = Form(None),
    group_col: Optional[str] = Form(None),
    patient_row_index: Optional[int] = Form(None),
):
    """
    Receive model + data, run:
      - global explanation
      - local explanation for one row
      - optional bias audit by group_col
    and return JSON consumed by the UI.
    """
    # Use a temporary directory to store uploaded files
    with tempfile.TemporaryDirectory() as tmpdir:
        model_path = os.path.join(tmpdir, model_file.filename or "model.pkl")
        data_path = os.path.join(tmpdir, data_file.filename or "data.csv")

        # Save model
        with open(model_path, "wb") as f:
            shutil.copyfileobj(model_file.file, f)
        # Save data
        with open(data_path, "wb") as f:
            shutil.copyfileobj(data_file.file, f)

        # Instantiate Explainer
        explainer = Explainer(
            model_path=model_path,
            data_path=data_path,
            feature_map=None,
            id_column=id_column or None,
            target=target or None,
        )

        # Global explanation
        global_res = explainer.run_global_explanation()

        # Local explanation
        kwargs = {}
        if patient_row_index is not None:
            kwargs["row_index"] = int(patient_row_index)
        local_res = explainer.run_local_explanation(
            patient_id=None if id_column is None else None,  # we could extend to select by id later
            **kwargs,
        )

        # Bias audit (optional)
        bias_res = None
        if group_col:
            try:
                bias_res = explainer.run_bias_audit(group_col=group_col)
            except Exception as e:
                bias_res = {"error": str(e)}

        return JSONResponse(
            {
                "global": global_res,
                "local": local_res,
                "bias": bias_res,
            }
        )
